apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixat
  labels:
    app: netflixat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflixat
  template:
    metadata:
      labels:
        app: netflixat
    spec:
      containers:
      - name: netflixat
        image: andresatl/finalat-devsecops:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: netflixat
  labels:
    app: netflixat
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: netflixat
