name: CI
on:
  push:
    branches:
      - feature-laboratorio-final-AndresTapia

jobs:
  Buildapp:
    runs-on: ubuntu-latest
    steps:

    #- name: Set up JDK 17
      #uses: actions/setup-java@v2 
      #with:
        #java-version: '17'
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install depencies
      run: npm install

    - name: Build
      run: npm run build

  SAST:
    needs: Buildapp
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      #with:
        #fetch-depth: 0
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install depencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Analisis SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        
    - name: SonarQube Quality Gate Check
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      uses: SonarSource/sonarqube-quality-gate-action@master
      
#--------------------- SCA -------------------------------------------
  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install depencies
      run: |
        npm install
        yarn install

    - name: Build
      run: npm run build

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '{{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 11
          --enableRetired
     
    - name: Upload Test result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck report
        path: ${{github.workspace}}/reports

# ----------------- Docker Build Image ----------------------------------------
  
  DockerBuild:
    needs: SCA
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3


    - name: Docker Build 
      run: |
        docker build -t andresatl/pruebavul:latest .

    - name: Prisma Cloud Scan
  # You may pin to the exact commit or the version.
  # uses: PaloAltoNetworks/prisma-cloud-scan@85c672286d19de64fb4d2277b532df64023d168a
      uses: PaloAltoNetworks/prisma-cloud-scan@v1.6.5
      with:
    # URL of your Prisma Cloud Compute Console
        pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
    # Username of a user with the CI user role
        pcc_user: ${{ secrets.PCC_CONSOLE_URL }}
    # Password of a user with the CI user role
        #pcc_pass: ${{ secrets.PCC_TOKEN }}
    # Name (or ID) of the image to be scanned
        image_name: andresatl/pruebavul:latest
    # Tenant project context for the command          

    #- name: Run Trivy vulnerability scanner
      #uses: aquasecurity/trivy-action@master
      #with:
        #image-ref: 'andresatl/pruebavul:latest'
        #ignore-unfixed: true 
        #format: 'table' 
    
    #- name: Docker Push 
      #run: |
        #docker push andresatl/finalat-devsecops:latest

#-------------------- Docker Scan ------------------------------------------

  #DockerScan:
    #needs: DockerBuild
    #runs-on: ubuntu-latest
    #steps:

    #- name: Docker Login
      #uses: docker/login-action@v3.0.0
      #with:
        #username: ${{ secrets.DOCKER_USER }}
       # password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Pull de la Imagen Docker
      #run: | 
        #docker pull andresatl/finalat-devsecops:latest

    #- name: Run Trivy vulnerability scanner
     # uses: aquasecurity/trivy-action@master
      #with:
        #image-ref: 'andresatl/finalat-devsecops:latest'
        #ignore-unfixed: true 
        #format: 'table'
        
    #- name: Upload scan results
      #uses: actions/upload-artifact@v2
      #with:
        #name: scan-results
       # path: ${{ github.workspace }}/trivy-results
        
    #- name: Push Docker
      #run: |
        #docker push andresatl/finalat-devsecops:latest

        
