name: CI
on:
  push:
    branches:
      - feature-laboratorio-final-AndresTapia

jobs:
  Buildapp:
    runs-on: ubuntu-latest
    steps:

    #- name: Set up JDK 17
      #uses: actions/setup-java@v2 
      #with:
        #java-version: '17'
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install depencies
      run: npm install

    - name: Build
      run: npm run build

  SAST:
    needs: Buildapp
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      #with:
        #fetch-depth: 0
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install depencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Analisis SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        
    - name: SonarQube Quality Gate Check
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      uses: SonarSource/sonarqube-quality-gate-action@master
      
#--------------------- SCA -------------------------------------------
  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install depencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Print Repository Name
      run: echo "Repository name:${{ github.event.repository.name }}"

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: 'Laboratorio-fina0-lAndresTapia'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired

          
    - name: Upload Test result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck report
        path: ${{github.workspace}}/reports
